sonar.projectKey=cloud-config-organization
sonar.sources=.
sonar.host.url=http://34.42.225.63:9000
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/*.test.js,**/*.spec.js,**/coverage/**,**/target/**,**/__pycache__/**

